name: Build Check # Needed for security reasons

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions: {}

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build ARABot
        run: |
          pnpm i
          pnpm run cleanBuild
